### ISSUE TITLE
vmware not displaying correctly

### ISSUE THREAD

**Issue by randomusert** [WyattSteinmann/CorgiOS#1]
vmware has a issue that it is too big resolution at least on my machine

**Comment by WyattSteinmann** [comment]
try editing the code to make it a smaller res then compiling it change width and height in the GUI Class To Your Res Or Just Wait Til CorgiOS 0.0.2 That Is Planed To Come Out 12/31/2024 Or Press The Full Screen Button In VMWare Or Just Boot To Console You Can Do That By Waiting For The Log To Say Booting CorgiOS Or Something Like That Then Hold C Then Hit F3 I Have A 1080p Screen So Sorry I Will Fix This In 0.0.2 Hope This Helped :D

**Comment by WyattSteinmann** [comment]
You Know What I Will Make A Micro Patch Will Come Out In Like A Hour

**Comment by WyattSteinmann** [comment]
Fixed On Patch 0.0.1_0002

**Comment by WyattSteinmann** [comment]
> vmware has a issue that it is too big resolution at least on my machine

Fixed Hope You Have Fun :D

**Comment by randomusert** [comment]
Ok. Eah My laptops resolution is quite weird so it could have a Been a thing that caused it but i Will try tommorrow

**Comment by WyattSteinmann** [comment]
> Ok. Eah My laptops resolution is quite weird so it could have a Been a thing that caused it but i Will try tommorrow

kay i just removed 1080p res and made it default keep in mind that i had to remove the wallpaper so i can fit

**Comment by WyattSteinmann** [comment]
> Ok. Eah My laptops resolution is quite weird so it could have a Been a thing that caused it but i Will try tommorrow

Btw Thanks For Looking At My Projects No One Does That So Just To Thank You I Followed You

**Comment by randomusert** [comment]
Hi. Good to hear i just like to see sometimes source code For projects but it primarly is on C#

**Comment by randomusert** [comment]
Also live The Windows XP wallpaper

**Comment by WyattSteinmann** [comment]
thanks

**Comment by WyattSteinmann** [comment]
Also If You Want You Can Make Your Own Distro Just Remember To Give Me Credit Thanks For Your Support

**Comment by randomusert** [comment]
Also If you want you can see My OS at https://github.com/tinteeam/tinos_version2 
Yeah very original name

**Comment by WyattSteinmann** [comment]
Oh Cool I Will Go Have A Look

**Comment by WyattSteinmann** [comment]
> Also If you want you can see My OS at https://github.com/tinteeam/tinos_version2 Yeah very original name

Can You Add A ISO In The Release That Be Nice I Will Still Go And Compile It Just Saying

**Comment by randomusert** [comment]
There IS a bunch of versions

**Comment by WyattSteinmann** [comment]
If You Need Ascii Do This In Before Run:
System.Console.OutputEncoding = Sys.ExtendedASCII.CosmosEncodingProvider.Instance.GetEncoding(437);

**Comment by randomusert** [comment]
Also The newest release is just a torrent file

**Comment by randomusert** [comment]
You can always submit a pull request to fix it

**Comment by randomusert** [comment]
I am going to sleep now since it 1.am in Finland currently

**Comment by WyattSteinmann** [comment]
Good Night
For Me Its 4:41

**Comment by WyattSteinmann** [comment]
But Bye :D
